name: Despliegue Automático en EC2

on:
  push:
    branches:
      - deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Conectar a la EC2 y Desplegar
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # 1. Crear carpeta y clonar el repositorio si no existe
            if [ ! -d "proyecto-eval2" ]; then
              git clone https://github.com/${{ github.repository }}.git proyecto-eval2
            fi
            
            # 2. Entrar a la carpeta y actualizar al último código
            cd proyecto-eval2
            git fetch --all
            git checkout deploy
            git pull origin deploy
            
            # 3. Detener contenedores viejos y construir los nuevos
            sudo docker-compose down
            sudo docker-compose up -d --build